/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ProjectModel {
  fullname: string;
  /**
   * Optional. If unset, preview chip will contain only icon. Useful, when you have wide icon
   */
  shortname?: string;
  description: string;
  /**
   * If you have wide logo, you should leave shortname empty
   */
  logoUrl: string;
  /**
   * An array of media files urls, presented on page of your project. It may be images, videos etc
   */
  files?: {
    url: string;
  }[];
  whitepaperUrl?: string;
  docsUrls?: {
    name?: string;
    url: string;
  }[];
  projectUrl: string;
  /**
   * The types of software, your project relates to
   */
  types: (
    | "app"
    | "cross-chain"
    | "community"
    | "dev"
    | "dex"
    | "defi"
    | "exchange"
    | "game"
    | "governance"
    | "nft"
    | "payment"
    | "service"
    | "staking"
    | "tools"
    | "wallet"
  )[];
  /**
   * Links to social networks of your projects. We support only described below
   */
  social: {
    twitter?: SocialLink[];
    discord?: SocialLink[];
    telegram?: SocialLink[];
  };
  launchDate?: string;
  token?: {
    name: string;
    chainId: number;
    symbol: string;
    decimals: number;
    address: string;
    logoURI: string;
    version: number;
  };
  /**
   * Keywords will help user to find your project in search !
   */
  keywords?: string[];
}
export interface SocialLink {
  link: string;
  hint?: string;
  /**
   * If undefined, will appear for any language
   */
  lang?: string;
}
